name: Premier workflow
on: workflow_dispatch
jobs:
    premier-job:
        runs-on: ubuntu-latest
        steps:
            - name: Dit bonjour
              run: echo "Hello world"
            - name: Dit au revoir
              run: echo "Goodbye !"
    second-job :
        name: Mon second job
        runs-on: ubuntu-latest
        steps:
            - name: Mon étape
              run: echo "je suis le second job !"
            
